/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\Users\\yougong\\Desktop\\友恭项目\\lfBlog\\blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-094abb17",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-094abb17").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7ae50b77",
    path: "/blogs/category1/2018/20180612.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ae50b77").then(next)
    },
  },
  {
    name: "v-73957bd7",
    path: "/blogs/category1/2018/20180213.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73957bd7").then(next)
    },
  },
  {
    name: "v-1cd4fc97",
    path: "/blogs/category1/2018/20181021.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1cd4fc97").then(next)
    },
  },
  {
    name: "v-b6aa8092",
    path: "/blogs/category1/2018/20181215.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b6aa8092").then(next)
    },
  },
  {
    name: "v-4a4e9b97",
    path: "/blogs/category1/2019/20190523.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a4e9b97").then(next)
    },
  },
  {
    name: "v-19b76f57",
    path: "/blogs/category1/2018/20180921.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19b76f57").then(next)
    },
  },
  {
    name: "v-d0c51152",
    path: "/blogs/category1/2020/20200316.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d0c51152").then(next)
    },
  },
  {
    name: "v-11e17f77",
    path: "/blogs/category1/2019/20190711.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11e17f77").then(next)
    },
  },
  {
    name: "v-40628037",
    path: "/blogs/category1/2018/20180122.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40628037").then(next)
    },
  },
  {
    name: "v-10814812",
    path: "/blogs/category1/2020/20200102.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-10814812").then(next)
    },
  },
  {
    name: "v-25688852",
    path: "/blogs/category1/2020/20200422.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25688852").then(next)
    },
  },
  {
    name: "v-7cf8a037",
    path: "/blogs/category1/2021/20210122.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7cf8a037").then(next)
    },
  },
  {
    name: "v-1b455357",
    path: "/blogs/category1/2022/20220305.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b455357").then(next)
    },
  },
  {
    name: "v-87a22892",
    path: "/blogs/category1/2022/20220522.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-87a22892").then(next)
    },
  },
  {
    name: "v-641bc912",
    path: "/blogs/category1/2022/20220601.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-641bc912").then(next)
    },
  },
  {
    name: "v-0b989bb7",
    path: "/blogs/category1/2020/20200621.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0b989bb7").then(next)
    },
  },
  {
    name: "v-4eb835c6",
    path: "/docs/CSS/flexbox.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4eb835c6").then(next)
    },
  },
  {
    name: "v-838f39cc",
    path: "/docs/CSS/accordion.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-838f39cc").then(next)
    },
  },
  {
    name: "v-4abcfdc4",
    path: "/docs/Html/BOM.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4abcfdc4").then(next)
    },
  },
  {
    name: "v-6b97719c",
    path: "/docs/CSS/loading.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b97719c").then(next)
    },
  },
  {
    name: "v-92fc4584",
    path: "/docs/CSS/shadow.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-92fc4584").then(next)
    },
  },
  {
    name: "v-22dff184",
    path: "/docs/Html/DOM.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-22dff184").then(next)
    },
  },
  {
    name: "v-b3ef43f8",
    path: "/docs/JS/Git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b3ef43f8").then(next)
    },
  },
  {
    name: "v-aba57620",
    path: "/docs/Vue/API.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aba57620").then(next)
    },
  },
  {
    name: "v-2cd156f7",
    path: "/docs/JS/%E5%B8%B8%E8%A7%81Api%E6%89%8B%E5%86%99.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2cd156f7").then(next)
    },
  },
  {
    path: "/docs/JS/常见Api手写.html",
    redirect: "/docs/JS/%E5%B8%B8%E8%A7%81Api%E6%89%8B%E5%86%99.html"
  },
  {
    name: "v-2af7a25e",
    path: "/docs/Vue/Data.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2af7a25e").then(next)
    },
  },
  {
    name: "v-0d35bb48",
    path: "/docs/JS/mobile.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d35bb48").then(next)
    },
  },
  {
    name: "v-0f2b9ffe",
    path: "/docs/Vue/asyncComponent.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f2b9ffe").then(next)
    },
  },
  {
    name: "v-8a26b844",
    path: "/docs/Vue/animationClass.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8a26b844").then(next)
    },
  },
  {
    name: "v-3acc9e28",
    path: "/docs/Vue/attribute.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3acc9e28").then(next)
    },
  },
  {
    name: "v-e636d4f4",
    path: "/docs/Vue/directive.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e636d4f4").then(next)
    },
  },
  {
    name: "v-17a17d70",
    path: "/docs/Vue/event.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-17a17d70").then(next)
    },
  },
  {
    name: "v-74f5182e",
    path: "/docs/Vue/filters.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74f5182e").then(next)
    },
  },
  {
    name: "v-978f5e44",
    path: "/docs/Vue/funComponent.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-978f5e44").then(next)
    },
  },
  {
    name: "v-b7ab5e04",
    path: "/docs/Vue/ref.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b7ab5e04").then(next)
    },
  },
  {
    name: "v-4abc9e12",
    path: "/docs/Vue/renderFun.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4abc9e12").then(next)
    },
  },
  {
    name: "v-e67bf844",
    path: "/docs/Vue/slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e67bf844").then(next)
    },
  },
  {
    name: "v-0da1b8de",
    path: "/docs/Vue/template.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0da1b8de").then(next)
    },
  },
  {
    name: "v-6c89b0de",
    path: "/docs/Vue/v-bind.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c89b0de").then(next)
    },
  },
  {
    name: "v-e3439c44",
    path: "/docs/Vue/v-if&v-for.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e3439c44").then(next)
    },
  },
  {
    name: "v-750dc504",
    path: "/docs/Vue/v-is.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-750dc504").then(next)
    },
  },
  {
    name: "v-44d25f80",
    path: "/docs/Vue/v-model.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44d25f80").then(next)
    },
  },
  {
    name: "v-1d83e864",
    path: "/docs/jottings/BOM.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d83e864").then(next)
    },
  },
  {
    name: "v-3fe60b24",
    path: "/docs/jottings/DOM.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3fe60b24").then(next)
    },
  },
  {
    name: "v-7406ddb8",
    path: "/docs/jottings/Git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7406ddb8").then(next)
    },
  },
  {
    name: "v-cf08afb8",
    path: "/docs/jottings/accordion.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cf08afb8").then(next)
    },
  },
  {
    name: "v-dde006b8",
    path: "/docs/jottings/flexbox.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dde006b8").then(next)
    },
  },
  {
    name: "v-da8ff538",
    path: "/docs/jottings/loading.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-da8ff538").then(next)
    },
  },
  {
    name: "v-6f20e7b4",
    path: "/docs/jottings/shadow.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f20e7b4").then(next)
    },
  },
  {
    name: "v-49a0cb16",
    path: "/docs/jottings/vueBuild.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49a0cb16").then(next)
    },
  },
  {
    name: "v-13eb74bc",
    path: "/docs/jottings/mobile.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13eb74bc").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-e8d965c8",
    path: "/tag/JS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e8d965c8").then(next)
    },
    meta: {"pid":"tags","id":"JS"}
  },
  {
    path: "/tag/JS/index.html",
    redirect: "/tag/JS/"
  },
  {
    name: "v-184d950c",
    path: "/tag/HTML/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-184d950c").then(next)
    },
    meta: {"pid":"tags","id":"HTML"}
  },
  {
    path: "/tag/HTML/index.html",
    redirect: "/tag/HTML/"
  },
  {
    name: "v-0c1cbc56",
    path: "/tag/正则/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0c1cbc56").then(next)
    },
    meta: {"pid":"tags","id":"正则"}
  },
  {
    path: "/tag/正则/index.html",
    redirect: "/tag/正则/"
  },
  {
    path: "/tag/%E6%AD%A3%E5%88%99/",
    redirect: "/tag/正则/"
  },
  {
    name: "v-c784ecce",
    path: "/tag/继承/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-c784ecce").then(next)
    },
    meta: {"pid":"tags","id":"继承"}
  },
  {
    path: "/tag/继承/index.html",
    redirect: "/tag/继承/"
  },
  {
    path: "/tag/%E7%BB%A7%E6%89%BF/",
    redirect: "/tag/继承/"
  },
  {
    name: "v-3446f207",
    path: "/tag/原型/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3446f207").then(next)
    },
    meta: {"pid":"tags","id":"原型"}
  },
  {
    path: "/tag/原型/index.html",
    redirect: "/tag/原型/"
  },
  {
    path: "/tag/%E5%8E%9F%E5%9E%8B/",
    redirect: "/tag/原型/"
  },
  {
    name: "v-fd10f050",
    path: "/tag/事件模型/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-fd10f050").then(next)
    },
    meta: {"pid":"tags","id":"事件模型"}
  },
  {
    path: "/tag/事件模型/index.html",
    redirect: "/tag/事件模型/"
  },
  {
    path: "/tag/%E4%BA%8B%E4%BB%B6%E6%A8%A1%E5%9E%8B/",
    redirect: "/tag/事件模型/"
  },
  {
    name: "v-d2055fbe",
    path: "/categories/前端小笔记/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-d2055fbe").then(next)
    },
    meta: {"pid":"categories","id":"前端小笔记"}
  },
  {
    path: "/categories/前端小笔记/index.html",
    redirect: "/categories/前端小笔记/"
  },
  {
    path: "/categories/%E5%89%8D%E7%AB%AF%E5%B0%8F%E7%AC%94%E8%AE%B0/",
    redirect: "/categories/前端小笔记/"
  },
  {
    name: "v-85672be2",
    path: "/categories/排序/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-85672be2").then(next)
    },
    meta: {"pid":"categories","id":"排序"}
  },
  {
    path: "/categories/排序/index.html",
    redirect: "/categories/排序/"
  },
  {
    path: "/categories/%E6%8E%92%E5%BA%8F/",
    redirect: "/categories/排序/"
  },
  {
    name: "v-3dfe3db2",
    path: "/categories/Promise/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-3dfe3db2").then(next)
    },
    meta: {"pid":"categories","id":"Promise"}
  },
  {
    path: "/categories/Promise/index.html",
    redirect: "/categories/Promise/"
  },
  {
    name: "v-75f01a3e",
    path: "/categories/正则/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-75f01a3e").then(next)
    },
    meta: {"pid":"categories","id":"正则"}
  },
  {
    path: "/categories/正则/index.html",
    redirect: "/categories/正则/"
  },
  {
    path: "/categories/%E6%AD%A3%E5%88%99/",
    redirect: "/categories/正则/"
  },
  {
    name: "v-6753daa5",
    path: "/categories/继承/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-6753daa5").then(next)
    },
    meta: {"pid":"categories","id":"继承"}
  },
  {
    path: "/categories/继承/index.html",
    redirect: "/categories/继承/"
  },
  {
    path: "/categories/%E7%BB%A7%E6%89%BF/",
    redirect: "/categories/继承/"
  },
  {
    name: "v-014579da",
    path: "/categories/原型/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-014579da").then(next)
    },
    meta: {"pid":"categories","id":"原型"}
  },
  {
    path: "/categories/原型/index.html",
    redirect: "/categories/原型/"
  },
  {
    path: "/categories/%E5%8E%9F%E5%9E%8B/",
    redirect: "/categories/原型/"
  },
  {
    name: "v-7ff82de4",
    path: "/categories/事件模型/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7ff82de4").then(next)
    },
    meta: {"pid":"categories","id":"事件模型"}
  },
  {
    path: "/categories/事件模型/index.html",
    redirect: "/categories/事件模型/"
  },
  {
    path: "/categories/%E4%BA%8B%E4%BB%B6%E6%A8%A1%E5%9E%8B/",
    redirect: "/categories/事件模型/"
  },
  {
    name: "v-7f71ddbe",
    path: "/tag/JS/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f71ddbe").then(next)
    },
    meta: {"pid":"tags","id":"JS"}
  },
  {
    path: "/tag/JS/page/2/index.html",
    redirect: "/tag/JS/page/2/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]