/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "前端小菜鸡",
  "description": "",
  "base": "/blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "https://www.zpzpup.com/assets/image/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "script",
      {
        "src": "/blog/assets/js/bodyClick.js"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Liu Blog",
        "tagline": "一个很菜的小前端",
        "heroTextStyle": {
          "color": "#fff"
        },
        "isShowTitleInHome": false
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-094abb17",
      "path": "/",
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.33kb"
    },
    {
      "title": "屏幕适配函数,（例子：图表中适用很香）",
      "frontmatter": {
        "title": "屏幕适配函数,（例子：图表中适用很香）",
        "date": "2018-06-12T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2018/20180612.html",
      "relativePath": "blogs/category1/2018/20180612.md",
      "key": "v-7ae50b77",
      "path": "/blogs/category1/2018/20180612.html",
      "headers": [
        {
          "level": 2,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 2,
          "title": "1.获取屏幕宽高对象",
          "slug": "_1-获取屏幕宽高对象"
        },
        {
          "level": 2,
          "title": "2.根据设置的屏幕宽高计算出适合的宽高",
          "slug": "_2-根据设置的屏幕宽高计算出适合的宽高"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.84kb"
    },
    {
      "title": "生成随机字符串",
      "frontmatter": {
        "title": "生成随机字符串",
        "date": "2018-02-13T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2018/20180213.html",
      "relativePath": "blogs/category1/2018/20180213.md",
      "key": "v-73957bd7",
      "path": "/blogs/category1/2018/20180213.html",
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.49kb"
    },
    {
      "title": "深拷贝 & 浅拷贝",
      "frontmatter": {
        "title": "深拷贝 & 浅拷贝",
        "date": "2018-10-21T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2018/20181021.html",
      "relativePath": "blogs/category1/2018/20181021.md",
      "key": "v-1cd4fc97",
      "path": "/blogs/category1/2018/20181021.html",
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "2.77kb"
    },
    {
      "title": "阻止冒泡",
      "frontmatter": {
        "title": "阻止冒泡",
        "date": "2018-12-15T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2018/20181215.html",
      "relativePath": "blogs/category1/2018/20181215.md",
      "key": "v-b6aa8092",
      "path": "/blogs/category1/2018/20181215.html",
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.43kb"
    },
    {
      "title": "函数柯里化",
      "frontmatter": {
        "title": "函数柯里化",
        "date": "2019-05-23T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2019/20190523.html",
      "relativePath": "blogs/category1/2019/20190523.md",
      "key": "v-4a4e9b97",
      "path": "/blogs/category1/2019/20190523.html",
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.37kb"
    },
    {
      "title": "阻止浏览器默认事件",
      "frontmatter": {
        "title": "阻止浏览器默认事件",
        "date": "2018-09-21T00:00:00.000Z",
        "tags": [
          "HTML"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2018/20180921.html",
      "relativePath": "blogs/category1/2018/20180921.md",
      "key": "v-19b76f57",
      "path": "/blogs/category1/2018/20180921.html",
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.27kb"
    },
    {
      "title": "节流&防抖",
      "frontmatter": {
        "title": "节流&防抖",
        "date": "2020-03-16T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2020/20200316.html",
      "relativePath": "blogs/category1/2020/20200316.md",
      "key": "v-d0c51152",
      "path": "/blogs/category1/2020/20200316.html",
      "headers": [
        {
          "level": 2,
          "title": "函数节流 throttle",
          "slug": "函数节流-throttle"
        },
        {
          "level": 2,
          "title": "函数防抖 debounce",
          "slug": "函数防抖-debounce"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "1.77kb"
    },
    {
      "title": "排序",
      "frontmatter": {
        "title": "排序",
        "date": "2019-07-11T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "排序"
        ],
        "sticky": true
      },
      "regularPath": "/blogs/category1/2019/20190711.html",
      "relativePath": "blogs/category1/2019/20190711.md",
      "key": "v-11e17f77",
      "path": "/blogs/category1/2019/20190711.html",
      "headers": [
        {
          "level": 2,
          "title": "冒泡排序",
          "slug": "冒泡排序"
        },
        {
          "level": 2,
          "title": "插入排序",
          "slug": "插入排序"
        },
        {
          "level": 2,
          "title": "快速排序",
          "slug": "快速排序"
        },
        {
          "level": 2,
          "title": "选择排序",
          "slug": "选择排序"
        },
        {
          "level": 2,
          "title": "归并排序",
          "slug": "归并排序"
        },
        {
          "level": 2,
          "title": "计数排序",
          "slug": "计数排序"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "3.42kb"
    },
    {
      "title": "随机生成数字",
      "frontmatter": {
        "title": "随机生成数字",
        "date": "2018-01-22T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2018/20180122.html",
      "relativePath": "blogs/category1/2018/20180122.md",
      "key": "v-40628037",
      "path": "/blogs/category1/2018/20180122.html",
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.76kb"
    },
    {
      "title": "call && apply",
      "frontmatter": {
        "title": "call && apply",
        "date": "2020-01-02T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2020/20200102.html",
      "relativePath": "blogs/category1/2020/20200102.md",
      "key": "v-10814812",
      "path": "/blogs/category1/2020/20200102.html",
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.54kb"
    },
    {
      "title": "Promise",
      "frontmatter": {
        "title": "Promise",
        "date": "2020-04-22T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "Promise"
        ]
      },
      "regularPath": "/blogs/category1/2020/20200422.html",
      "relativePath": "blogs/category1/2020/20200422.md",
      "key": "v-25688852",
      "path": "/blogs/category1/2020/20200422.html",
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "5.32kb"
    },
    {
      "title": "常用正则表达式",
      "frontmatter": {
        "title": "常用正则表达式",
        "date": "2021-01-22T00:00:00.000Z",
        "tags": [
          "正则"
        ],
        "categories": [
          "正则"
        ],
        "sticky": true
      },
      "regularPath": "/blogs/category1/2021/20210122.html",
      "relativePath": "blogs/category1/2021/20210122.md",
      "key": "v-7cf8a037",
      "path": "/blogs/category1/2021/20210122.html",
      "headers": [
        {
          "level": 2,
          "title": "1.校验数字的表达式",
          "slug": "_1-校验数字的表达式"
        },
        {
          "level": 2,
          "title": "2.校验字符的表达式",
          "slug": "_2-校验字符的表达式"
        },
        {
          "level": 2,
          "title": "3.特殊需求表达式",
          "slug": "_3-特殊需求表达式"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "4.29kb"
    },
    {
      "title": "继承",
      "frontmatter": {
        "title": "继承",
        "date": "2022-03-05T00:00:00.000Z",
        "tags": [
          "继承"
        ],
        "categories": [
          "继承"
        ],
        "sticky": false
      },
      "regularPath": "/blogs/category1/2022/20220305.html",
      "relativePath": "blogs/category1/2022/20220305.md",
      "key": "v-1b455357",
      "path": "/blogs/category1/2022/20220305.html",
      "headers": [
        {
          "level": 2,
          "title": "一、是什么",
          "slug": "一、是什么"
        },
        {
          "level": 2,
          "title": "二、实现方式",
          "slug": "二、实现方式"
        },
        {
          "level": 3,
          "title": "原型链继承",
          "slug": "原型链继承"
        },
        {
          "level": 3,
          "title": "构造函数继承",
          "slug": "构造函数继承"
        },
        {
          "level": 3,
          "title": "组合继承",
          "slug": "组合继承"
        },
        {
          "level": 3,
          "title": "原型式继承",
          "slug": "原型式继承"
        },
        {
          "level": 3,
          "title": "寄生式继承",
          "slug": "寄生式继承"
        },
        {
          "level": 3,
          "title": "寄生组合式继承",
          "slug": "寄生组合式继承"
        },
        {
          "level": 2,
          "title": "三、总结",
          "slug": "三、总结"
        }
      ],
      "size": "5.77kb"
    },
    {
      "title": "原型和原型链理解",
      "frontmatter": {
        "title": "原型和原型链理解",
        "date": "2022-05-22T00:00:00.000Z",
        "tags": [
          "原型"
        ],
        "categories": [
          "原型"
        ],
        "sticky": true
      },
      "regularPath": "/blogs/category1/2022/20220522.html",
      "relativePath": "blogs/category1/2022/20220522.md",
      "key": "v-87a22892",
      "path": "/blogs/category1/2022/20220522.html",
      "headers": [
        {
          "level": 2,
          "title": "一：原型、原型链相等关系理解",
          "slug": "一：原型、原型链相等关系理解"
        },
        {
          "level": 2,
          "title": "二：原型、原型链的意思何在",
          "slug": "二：原型、原型链的意思何在"
        }
      ],
      "size": "4.03kb"
    },
    {
      "title": "JS事件模型",
      "frontmatter": {
        "title": "JS事件模型",
        "date": "2022-06-01T00:00:00.000Z",
        "tags": [
          "事件模型"
        ],
        "categories": [
          "事件模型"
        ],
        "sticky": false
      },
      "regularPath": "/blogs/category1/2022/20220601.html",
      "relativePath": "blogs/category1/2022/20220601.md",
      "key": "v-641bc912",
      "path": "/blogs/category1/2022/20220601.html",
      "headers": [
        {
          "level": 2,
          "title": "一、事件与事件流",
          "slug": "一、事件与事件流"
        },
        {
          "level": 2,
          "title": "#二、事件模型",
          "slug": "二、事件模型"
        },
        {
          "level": 3,
          "title": "#原始事件模型",
          "slug": "原始事件模型"
        },
        {
          "level": 3,
          "title": "#标准事件模型",
          "slug": "标准事件模型"
        },
        {
          "level": 3,
          "title": "#IE事件模型",
          "slug": "ie事件模型"
        }
      ],
      "size": "4.43kb"
    },
    {
      "title": "Base64转blob对象",
      "frontmatter": {
        "title": "Base64转blob对象",
        "date": "2020-06-21T00:00:00.000Z",
        "tags": [
          "JS"
        ],
        "categories": [
          "前端小笔记"
        ]
      },
      "regularPath": "/blogs/category1/2020/20200621.html",
      "relativePath": "blogs/category1/2020/20200621.md",
      "key": "v-0b989bb7",
      "path": "/blogs/category1/2020/20200621.html",
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.49kb"
    },
    {
      "title": "flex布局",
      "frontmatter": {
        "title": "flex布局",
        "date": "2020-11-06T00:00:00.000Z"
      },
      "regularPath": "/docs/CSS/flexbox.html",
      "relativePath": "docs/CSS/flexbox.md",
      "key": "v-4eb835c6",
      "path": "/docs/CSS/flexbox.html",
      "headers": [
        {
          "level": 2,
          "title": "live demo",
          "slug": "live-demo"
        },
        {
          "level": 2,
          "title": "属性解释",
          "slug": "属性解释"
        },
        {
          "level": 3,
          "title": "flexbox",
          "slug": "flexbox"
        },
        {
          "level": 3,
          "title": "flex-direction",
          "slug": "flex-direction"
        },
        {
          "level": 3,
          "title": "flex-wrap",
          "slug": "flex-wrap"
        },
        {
          "level": 3,
          "title": "flex-flow",
          "slug": "flex-flow"
        },
        {
          "level": 3,
          "title": "justify-content",
          "slug": "justify-content"
        },
        {
          "level": 3,
          "title": "align-items",
          "slug": "align-items"
        },
        {
          "level": 3,
          "title": "align-content",
          "slug": "align-content"
        },
        {
          "level": 3,
          "title": "order",
          "slug": "order"
        },
        {
          "level": 3,
          "title": "flex-basis",
          "slug": "flex-basis"
        },
        {
          "level": 3,
          "title": "flex-grow",
          "slug": "flex-grow"
        },
        {
          "level": 3,
          "title": "flex-shrink",
          "slug": "flex-shrink"
        },
        {
          "level": 3,
          "title": "align-self",
          "slug": "align-self"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "2.98kb"
    },
    {
      "title": "手风琴",
      "frontmatter": {
        "title": "手风琴",
        "date": "2020-08-12T00:00:00.000Z"
      },
      "regularPath": "/docs/CSS/accordion.html",
      "relativePath": "docs/CSS/accordion.md",
      "key": "v-838f39cc",
      "path": "/docs/CSS/accordion.html",
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "1.34kb"
    },
    {
      "title": "BOM对象",
      "frontmatter": {
        "title": "BOM对象",
        "date": "2021-01-20T00:00:00.000Z"
      },
      "regularPath": "/docs/Html/BOM.html",
      "relativePath": "docs/Html/BOM.md",
      "key": "v-4abcfdc4",
      "path": "/docs/Html/BOM.html",
      "headers": [
        {
          "level": 2,
          "title": "判读浏览器是否支持 CSS 属性",
          "slug": "判读浏览器是否支持-css-属性"
        },
        {
          "level": 2,
          "title": "返回当前网页地址",
          "slug": "返回当前网页地址"
        },
        {
          "level": 2,
          "title": "获取滚动条位置",
          "slug": "获取滚动条位置"
        },
        {
          "level": 2,
          "title": "获取url中的参数",
          "slug": "获取url中的参数"
        },
        {
          "level": 2,
          "title": "页面跳转，是否记录在history中",
          "slug": "页面跳转，是否记录在history中"
        },
        {
          "level": 2,
          "title": "滚动条滚动到指定位置",
          "slug": "滚动条滚动到指定位置"
        },
        {
          "level": 2,
          "title": "复制文本",
          "slug": "复制文本"
        },
        {
          "level": 2,
          "title": "检测设备类型",
          "slug": "检测设备类型"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "4.91kb"
    },
    {
      "title": "loading 加载动画",
      "frontmatter": {
        "title": "loading 加载动画",
        "date": "2020-09-15T00:00:00.000Z"
      },
      "regularPath": "/docs/CSS/loading.html",
      "relativePath": "docs/CSS/loading.md",
      "key": "v-6b97719c",
      "path": "/docs/CSS/loading.html",
      "headers": [
        {
          "level": 2,
          "title": "loading_2",
          "slug": "loading-2"
        },
        {
          "level": 2,
          "title": "loading_3",
          "slug": "loading-3"
        },
        {
          "level": 2,
          "title": "loading_4",
          "slug": "loading-4"
        },
        {
          "level": 2,
          "title": "loading_5",
          "slug": "loading-5"
        },
        {
          "level": 2,
          "title": "loading_6",
          "slug": "loading-6"
        },
        {
          "level": 2,
          "title": "loading_7",
          "slug": "loading-7"
        },
        {
          "level": 2,
          "title": "相关项目",
          "slug": "相关项目"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "10.75kb"
    },
    {
      "title": "常见阴影",
      "frontmatter": {
        "title": "常见阴影",
        "date": "2019-06-21T00:00:00.000Z"
      },
      "regularPath": "/docs/CSS/shadow.html",
      "relativePath": "docs/CSS/shadow.md",
      "key": "v-92fc4584",
      "path": "/docs/CSS/shadow.html",
      "headers": [
        {
          "level": 2,
          "title": "常见投影",
          "slug": "常见投影"
        },
        {
          "level": 2,
          "title": "不规则图形投影",
          "slug": "不规则图形投影"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "2.30kb"
    },
    {
      "title": "DOM操作",
      "frontmatter": {
        "title": "DOM操作",
        "date": "2021-01-12T00:00:00.000Z"
      },
      "regularPath": "/docs/Html/DOM.html",
      "relativePath": "docs/Html/DOM.md",
      "key": "v-22dff184",
      "path": "/docs/Html/DOM.html",
      "headers": [
        {
          "level": 2,
          "title": "固定滚动条",
          "slug": "固定滚动条"
        },
        {
          "level": 2,
          "title": "判断当前位置是否为页面底部",
          "slug": "判断当前位置是否为页面底部"
        },
        {
          "level": 2,
          "title": "判断元素是否在可视范围内",
          "slug": "判断元素是否在可视范围内"
        },
        {
          "level": 2,
          "title": "获取元素css样式",
          "slug": "获取元素css样式"
        },
        {
          "level": 2,
          "title": "进入全屏",
          "slug": "进入全屏"
        },
        {
          "level": 2,
          "title": "退出全屏",
          "slug": "退出全屏"
        },
        {
          "level": 2,
          "title": "全屏事件",
          "slug": "全屏事件"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "2.62kb"
    },
    {
      "title": "Git",
      "frontmatter": {
        "title": "Git",
        "date": "2021-02-22T00:00:00.000Z"
      },
      "regularPath": "/docs/JS/Git.html",
      "relativePath": "docs/JS/Git.md",
      "key": "v-b3ef43f8",
      "path": "/docs/JS/Git.html",
      "headers": [
        {
          "level": 2,
          "title": "常用命令",
          "slug": "常用命令"
        },
        {
          "level": 2,
          "title": "Git 相关",
          "slug": "git-相关"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "5.24kb"
    },
    {
      "title": "全局API",
      "frontmatter": {
        "title": "全局API",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/API.html",
      "relativePath": "docs/Vue/API.md",
      "key": "v-aba57620",
      "path": "/docs/Vue/API.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue2",
          "slug": "vue2"
        },
        {
          "level": 2,
          "title": "Vue3",
          "slug": "vue3"
        },
        {
          "level": 3,
          "title": "提供/注入 (Provide / Inject)",
          "slug": "提供-注入-provide-inject"
        },
        {
          "level": 3,
          "title": "工厂",
          "slug": "工厂"
        },
        {
          "level": 3,
          "title": "nextTick",
          "slug": "nexttick"
        },
        {
          "level": 3,
          "title": "v-if v-else v-else-if",
          "slug": "v-if-v-else-v-else-if"
        },
        {
          "level": 3,
          "title": "",
          "slug": "template-v-for"
        },
        {
          "level": 3,
          "title": "按键修饰符",
          "slug": "按键修饰符"
        },
        {
          "level": 3,
          "title": "在 prop 的默认函数中访问 this",
          "slug": "在-prop-的默认函数中访问-this"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "3.54kb"
    },
    {
      "title": "常见Api手写",
      "frontmatter": {
        "title": "常见Api手写",
        "date": "2023-01-03T00:00:00.000Z"
      },
      "regularPath": "/docs/JS/%E5%B8%B8%E8%A7%81Api%E6%89%8B%E5%86%99.html",
      "relativePath": "docs/JS/常见Api手写.md",
      "key": "v-2cd156f7",
      "path": "/docs/JS/%E5%B8%B8%E8%A7%81Api%E6%89%8B%E5%86%99.html",
      "headers": [
        {
          "level": 2,
          "title": "instanceof",
          "slug": "instanceof"
        },
        {
          "level": 2,
          "title": "new的实现",
          "slug": "new的实现"
        },
        {
          "level": 2,
          "title": "深拷贝",
          "slug": "深拷贝"
        },
        {
          "level": 2,
          "title": "ajax实现",
          "slug": "ajax实现"
        }
      ],
      "size": "2.82kb"
    },
    {
      "title": "Data",
      "frontmatter": {
        "title": "Data",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/Data.html",
      "relativePath": "docs/Vue/Data.md",
      "key": "v-2af7a25e",
      "path": "/docs/Vue/Data.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue2",
          "slug": "vue2"
        },
        {
          "level": 2,
          "title": "Vue3",
          "slug": "vue3"
        },
        {
          "level": 2,
          "title": "Mixin 合并行为变更",
          "slug": "mixin-合并行为变更"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "1.12kb"
    },
    {
      "title": "移动端踩坑指南",
      "frontmatter": {
        "title": "移动端踩坑指南",
        "date": "2021-01-28T00:00:00.000Z"
      },
      "regularPath": "/docs/JS/mobile.html",
      "relativePath": "docs/JS/mobile.md",
      "key": "v-0d35bb48",
      "path": "/docs/JS/mobile.html",
      "headers": [
        {
          "level": 2,
          "title": "HTML方向",
          "slug": "html方向"
        },
        {
          "level": 3,
          "title": "调用系统功能",
          "slug": "调用系统功能"
        },
        {
          "level": 3,
          "title": "忽略自动识别",
          "slug": "忽略自动识别"
        },
        {
          "level": 3,
          "title": "弹出数字键盘",
          "slug": "弹出数字键盘"
        },
        {
          "level": 3,
          "title": "唤醒原生应用",
          "slug": "唤醒原生应用"
        },
        {
          "level": 3,
          "title": "禁止页面缩放",
          "slug": "禁止页面缩放"
        },
        {
          "level": 3,
          "title": "禁止页面缓存",
          "slug": "禁止页面缓存"
        },
        {
          "level": 3,
          "title": "禁止字母大写",
          "slug": "禁止字母大写"
        },
        {
          "level": 3,
          "title": "针对Safari配置",
          "slug": "针对safari配置"
        },
        {
          "level": 3,
          "title": "针对其他浏览器配置",
          "slug": "针对其他浏览器配置"
        },
        {
          "level": 3,
          "title": "让:active有效，让:hover无效",
          "slug": "让-active有效，让-hover无效"
        },
        {
          "level": 2,
          "title": "CSS方向",
          "slug": "css方向"
        },
        {
          "level": 3,
          "title": "自动适应布局",
          "slug": "自动适应布局"
        },
        {
          "level": 3,
          "title": "自动适应背景",
          "slug": "自动适应背景"
        },
        {
          "level": 3,
          "title": "监听屏幕旋转",
          "slug": "监听屏幕旋转"
        },
        {
          "level": 3,
          "title": "支持弹性滚动",
          "slug": "支持弹性滚动"
        },
        {
          "level": 3,
          "title": "禁止滚动传播",
          "slug": "禁止滚动传播"
        },
        {
          "level": 3,
          "title": "禁止屏幕抖动",
          "slug": "禁止屏幕抖动"
        },
        {
          "level": 3,
          "title": "禁止长按操作",
          "slug": "禁止长按操作"
        },
        {
          "level": 3,
          "title": "禁止字体调整",
          "slug": "禁止字体调整"
        },
        {
          "level": 3,
          "title": "禁止高亮显示",
          "slug": "禁止高亮显示"
        },
        {
          "level": 3,
          "title": "禁止动画闪屏",
          "slug": "禁止动画闪屏"
        },
        {
          "level": 3,
          "title": "美化表单外观",
          "slug": "美化表单外观"
        },
        {
          "level": 3,
          "title": "美化滚动占位",
          "slug": "美化滚动占位"
        },
        {
          "level": 3,
          "title": "美化输入占位",
          "slug": "美化输入占位"
        },
        {
          "level": 3,
          "title": "对齐输入占位",
          "slug": "对齐输入占位"
        },
        {
          "level": 3,
          "title": "对齐下拉选项",
          "slug": "对齐下拉选项"
        },
        {
          "level": 3,
          "title": "修复点击无效",
          "slug": "修复点击无效"
        },
        {
          "level": 3,
          "title": "识别文本换行",
          "slug": "识别文本换行"
        },
        {
          "level": 3,
          "title": "开启硬件加速",
          "slug": "开启硬件加速"
        },
        {
          "level": 3,
          "title": "描绘像素边框",
          "slug": "描绘像素边框"
        },
        {
          "level": 3,
          "title": "控制溢出文本",
          "slug": "控制溢出文本"
        },
        {
          "level": 2,
          "title": "JS方向",
          "slug": "js方向"
        },
        {
          "level": 3,
          "title": "禁止点击穿透",
          "slug": "禁止点击穿透"
        },
        {
          "level": 3,
          "title": "禁止滑动穿透",
          "slug": "禁止滑动穿透"
        },
        {
          "level": 3,
          "title": "支持往返刷新",
          "slug": "支持往返刷新"
        },
        {
          "level": 3,
          "title": "解析有效日期",
          "slug": "解析有效日期"
        },
        {
          "level": 3,
          "title": "修复输入监听",
          "slug": "修复输入监听"
        },
        {
          "level": 3,
          "title": "简化回到顶部",
          "slug": "简化回到顶部"
        },
        {
          "level": 3,
          "title": "简化懒性加载",
          "slug": "简化懒性加载"
        },
        {
          "level": 3,
          "title": "优化扫码识别",
          "slug": "优化扫码识别"
        },
        {
          "level": 3,
          "title": "自动播放媒体",
          "slug": "自动播放媒体"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "15.80kb"
    },
    {
      "title": "异步组件",
      "frontmatter": {
        "title": "异步组件",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/asyncComponent.html",
      "relativePath": "docs/Vue/asyncComponent.md",
      "key": "v-0f2b9ffe",
      "path": "/docs/Vue/asyncComponent.html",
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "1.12kb"
    },
    {
      "title": "过渡class变化",
      "frontmatter": {
        "title": "过渡class变化",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/animationClass.html",
      "relativePath": "docs/Vue/animationClass.md",
      "key": "v-8a26b844",
      "path": "/docs/Vue/animationClass.html",
      "headers": [
        {
          "level": 2,
          "title": "2.x 语法",
          "slug": "_2-x-语法"
        },
        {
          "level": 2,
          "title": "3.x 语法",
          "slug": "_3-x-语法"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.48kb"
    },
    {
      "title": "attribute 强制行为",
      "frontmatter": {
        "title": "attribute 强制行为",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/attribute.html",
      "relativePath": "docs/Vue/attribute.md",
      "key": "v-3acc9e28",
      "path": "/docs/Vue/attribute.html",
      "headers": [
        {
          "level": 2,
          "title": "布尔属性",
          "slug": "布尔属性"
        },
        {
          "level": 2,
          "title": "枚举属性",
          "slug": "枚举属性"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "1.97kb"
    },
    {
      "title": "directive 指令",
      "frontmatter": {
        "title": "directive 指令",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/directive.html",
      "relativePath": "docs/Vue/directive.md",
      "key": "v-e636d4f4",
      "path": "/docs/Vue/directive.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue2",
          "slug": "vue2"
        },
        {
          "level": 2,
          "title": "Vue3",
          "slug": "vue3"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "1.26kb"
    },
    {
      "title": "Event",
      "frontmatter": {
        "title": "Event",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/event.html",
      "relativePath": "docs/Vue/event.md",
      "key": "v-17a17d70",
      "path": "/docs/Vue/event.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue2",
          "slug": "vue2"
        },
        {
          "level": 2,
          "title": "Vue3",
          "slug": "vue3"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.92kb"
    },
    {
      "title": "filters",
      "frontmatter": {
        "title": "filters",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/filters.html",
      "relativePath": "docs/Vue/filters.md",
      "key": "v-74f5182e",
      "path": "/docs/Vue/filters.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue2",
          "slug": "vue2"
        },
        {
          "level": 2,
          "title": "Vue3",
          "slug": "vue3"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.79kb"
    },
    {
      "title": "函数式组件",
      "frontmatter": {
        "title": "函数式组件",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/funComponent.html",
      "relativePath": "docs/Vue/funComponent.md",
      "key": "v-978f5e44",
      "path": "/docs/Vue/funComponent.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue2",
          "slug": "vue2"
        },
        {
          "level": 2,
          "title": "Vue3",
          "slug": "vue3"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.91kb"
    },
    {
      "title": "Ref区别",
      "frontmatter": {
        "title": "Ref区别",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/ref.html",
      "relativePath": "docs/Vue/ref.md",
      "key": "v-b7ab5e04",
      "path": "/docs/Vue/ref.html",
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.63kb"
    },
    {
      "title": "渲染函数",
      "frontmatter": {
        "title": "渲染函数",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/renderFun.html",
      "relativePath": "docs/Vue/renderFun.md",
      "key": "v-4abc9e12",
      "path": "/docs/Vue/renderFun.html",
      "headers": [
        {
          "level": 3,
          "title": "渲染函数参数Props",
          "slug": "渲染函数参数props"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "1.07kb"
    },
    {
      "title": "slot统一",
      "frontmatter": {
        "title": "slot统一",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/slot.html",
      "relativePath": "docs/Vue/slot.md",
      "key": "v-e67bf844",
      "path": "/docs/Vue/slot.html",
      "headers": [
        {
          "level": 2,
          "title": "2.x 语法",
          "slug": "_2-x-语法"
        },
        {
          "level": 2,
          "title": "3.x 语法",
          "slug": "_3-x-语法"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.62kb"
    },
    {
      "title": "片段",
      "frontmatter": {
        "title": "片段",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/template.html",
      "relativePath": "docs/Vue/template.md",
      "key": "v-0da1b8de",
      "path": "/docs/Vue/template.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue2",
          "slug": "vue2"
        },
        {
          "level": 2,
          "title": "Vue3",
          "slug": "vue3"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.44kb"
    },
    {
      "title": "v-bind",
      "frontmatter": {
        "title": "v-bind",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/v-bind.html",
      "relativePath": "docs/Vue/v-bind.md",
      "key": "v-6c89b0de",
      "path": "/docs/Vue/v-bind.html",
      "headers": [
        {
          "level": 2,
          "title": "2.x 语法",
          "slug": "_2-x-语法"
        },
        {
          "level": 2,
          "title": "3.x 语法",
          "slug": "_3-x-语法"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.57kb"
    },
    {
      "title": "v-if 与 v-for 的优先级对比",
      "frontmatter": {
        "title": "v-if 与 v-for 的优先级对比",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/v-if&v-for.html",
      "relativePath": "docs/Vue/v-if&v-for.md",
      "key": "v-e3439c44",
      "path": "/docs/Vue/v-if&v-for.html",
      "headers": [
        {
          "level": 2,
          "title": "2.x 语法",
          "slug": "_2-x-语法"
        },
        {
          "level": 2,
          "title": "3.x 语法",
          "slug": "_3-x-语法"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.20kb"
    },
    {
      "title": "v-is",
      "frontmatter": {
        "title": "v-is",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/v-is.html",
      "relativePath": "docs/Vue/v-is.md",
      "key": "v-750dc504",
      "path": "/docs/Vue/v-is.html",
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "0.37kb"
    },
    {
      "title": "v-model",
      "frontmatter": {
        "title": "v-model",
        "date": "2021-03-11T00:00:00.000Z"
      },
      "regularPath": "/docs/Vue/v-model.html",
      "relativePath": "docs/Vue/v-model.md",
      "key": "v-44d25f80",
      "path": "/docs/Vue/v-model.html",
      "headers": [
        {
          "level": 2,
          "title": "Vue2. x",
          "slug": "vue2-x"
        },
        {
          "level": 2,
          "title": "vue3. x",
          "slug": "vue3-x"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "1.21kb"
    },
    {
      "title": "BOM对象",
      "frontmatter": {
        "title": "BOM对象",
        "date": "2021-01-20T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/BOM.html",
      "relativePath": "docs/jottings/BOM.md",
      "key": "v-1d83e864",
      "path": "/docs/jottings/BOM.html",
      "headers": [
        {
          "level": 2,
          "title": "判读浏览器是否支持 CSS 属性",
          "slug": "判读浏览器是否支持-css-属性"
        },
        {
          "level": 2,
          "title": "返回当前网页地址",
          "slug": "返回当前网页地址"
        },
        {
          "level": 2,
          "title": "获取滚动条位置",
          "slug": "获取滚动条位置"
        },
        {
          "level": 2,
          "title": "获取url中的参数",
          "slug": "获取url中的参数"
        },
        {
          "level": 2,
          "title": "页面跳转，是否记录在history中",
          "slug": "页面跳转，是否记录在history中"
        },
        {
          "level": 2,
          "title": "滚动条滚动到指定位置",
          "slug": "滚动条滚动到指定位置"
        },
        {
          "level": 2,
          "title": "复制文本",
          "slug": "复制文本"
        },
        {
          "level": 2,
          "title": "检测设备类型",
          "slug": "检测设备类型"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "4.91kb"
    },
    {
      "title": "DOM操作",
      "frontmatter": {
        "title": "DOM操作",
        "date": "2021-01-12T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/DOM.html",
      "relativePath": "docs/jottings/DOM.md",
      "key": "v-3fe60b24",
      "path": "/docs/jottings/DOM.html",
      "headers": [
        {
          "level": 2,
          "title": "固定滚动条",
          "slug": "固定滚动条"
        },
        {
          "level": 2,
          "title": "判断当前位置是否为页面底部",
          "slug": "判断当前位置是否为页面底部"
        },
        {
          "level": 2,
          "title": "判断元素是否在可视范围内",
          "slug": "判断元素是否在可视范围内"
        },
        {
          "level": 2,
          "title": "获取元素css样式",
          "slug": "获取元素css样式"
        },
        {
          "level": 2,
          "title": "进入全屏",
          "slug": "进入全屏"
        },
        {
          "level": 2,
          "title": "退出全屏",
          "slug": "退出全屏"
        },
        {
          "level": 2,
          "title": "全屏事件",
          "slug": "全屏事件"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "2.62kb"
    },
    {
      "title": "Git",
      "frontmatter": {
        "title": "Git",
        "date": "2021-02-22T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/Git.html",
      "relativePath": "docs/jottings/Git.md",
      "key": "v-7406ddb8",
      "path": "/docs/jottings/Git.html",
      "headers": [
        {
          "level": 2,
          "title": "常用命令",
          "slug": "常用命令"
        },
        {
          "level": 2,
          "title": "Git 相关",
          "slug": "git-相关"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "5.24kb"
    },
    {
      "title": "手风琴",
      "frontmatter": {
        "title": "手风琴",
        "date": "2020-08-12T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/accordion.html",
      "relativePath": "docs/jottings/accordion.md",
      "key": "v-cf08afb8",
      "path": "/docs/jottings/accordion.html",
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "1.34kb"
    },
    {
      "title": "flex布局",
      "frontmatter": {
        "title": "flex布局",
        "date": "2020-11-06T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/flexbox.html",
      "relativePath": "docs/jottings/flexbox.md",
      "key": "v-dde006b8",
      "path": "/docs/jottings/flexbox.html",
      "headers": [
        {
          "level": 2,
          "title": "live demo",
          "slug": "live-demo"
        },
        {
          "level": 2,
          "title": "属性解释",
          "slug": "属性解释"
        },
        {
          "level": 3,
          "title": "flexbox",
          "slug": "flexbox"
        },
        {
          "level": 3,
          "title": "flex-direction",
          "slug": "flex-direction"
        },
        {
          "level": 3,
          "title": "flex-wrap",
          "slug": "flex-wrap"
        },
        {
          "level": 3,
          "title": "flex-flow",
          "slug": "flex-flow"
        },
        {
          "level": 3,
          "title": "justify-content",
          "slug": "justify-content"
        },
        {
          "level": 3,
          "title": "align-items",
          "slug": "align-items"
        },
        {
          "level": 3,
          "title": "align-content",
          "slug": "align-content"
        },
        {
          "level": 3,
          "title": "order",
          "slug": "order"
        },
        {
          "level": 3,
          "title": "flex-basis",
          "slug": "flex-basis"
        },
        {
          "level": 3,
          "title": "flex-grow",
          "slug": "flex-grow"
        },
        {
          "level": 3,
          "title": "flex-shrink",
          "slug": "flex-shrink"
        },
        {
          "level": 3,
          "title": "align-self",
          "slug": "align-self"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "2.98kb"
    },
    {
      "title": "loading 加载动画",
      "frontmatter": {
        "title": "loading 加载动画",
        "date": "2020-09-15T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/loading.html",
      "relativePath": "docs/jottings/loading.md",
      "key": "v-da8ff538",
      "path": "/docs/jottings/loading.html",
      "headers": [
        {
          "level": 2,
          "title": "loading_2",
          "slug": "loading-2"
        },
        {
          "level": 2,
          "title": "loading_3",
          "slug": "loading-3"
        },
        {
          "level": 2,
          "title": "loading_4",
          "slug": "loading-4"
        },
        {
          "level": 2,
          "title": "loading_5",
          "slug": "loading-5"
        },
        {
          "level": 2,
          "title": "loading_6",
          "slug": "loading-6"
        },
        {
          "level": 2,
          "title": "loading_7",
          "slug": "loading-7"
        },
        {
          "level": 2,
          "title": "相关项目",
          "slug": "相关项目"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "10.75kb"
    },
    {
      "title": "常见阴影",
      "frontmatter": {
        "title": "常见阴影",
        "date": "2019-06-21T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/shadow.html",
      "relativePath": "docs/jottings/shadow.md",
      "key": "v-6f20e7b4",
      "path": "/docs/jottings/shadow.html",
      "headers": [
        {
          "level": 2,
          "title": "常见投影",
          "slug": "常见投影"
        },
        {
          "level": 2,
          "title": "不规则图形投影",
          "slug": "不规则图形投影"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "2.30kb"
    },
    {
      "title": "关于 Vue 项目打包部署知识点总结",
      "frontmatter": {
        "title": "关于 Vue 项目打包部署知识点总结",
        "date": "2021-11-16T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/vueBuild.html",
      "relativePath": "docs/jottings/vueBuild.md",
      "key": "v-49a0cb16",
      "path": "/docs/jottings/vueBuild.html",
      "headers": [
        {
          "level": 2,
          "title": "1. 准备一台服务器",
          "slug": "_1-准备一台服务器"
        },
        {
          "level": 2,
          "title": "2. nginx安装和启动",
          "slug": "_2-nginx安装和启动"
        },
        {
          "level": 2,
          "title": "3、 了解nginx: 修改nginx配置，让nginx服务器代理我们创建的文件",
          "slug": "_3、-了解nginx-修改nginx配置，让nginx服务器代理我们创建的文件"
        },
        {
          "level": 3,
          "title": "1、创建文件夹/www，并创建index.html，写入\"Hello world\"字符串",
          "slug": "_1、创建文件夹-www，并创建index-html，写入-hello-world-字符串"
        },
        {
          "level": 3,
          "title": "2、修改root值为 /www",
          "slug": "_2、修改root值为-www"
        },
        {
          "level": 3,
          "title": "3、sudo nginx -t 检查nginx配置是否正确",
          "slug": "_3、sudo-nginx-t-检查nginx配置是否正确"
        },
        {
          "level": 3,
          "title": "4、加载nginx配置：sudo nginx -s reload",
          "slug": "_4、加载nginx配置：sudo-nginx-s-reload"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "1.72kb"
    },
    {
      "title": "移动端踩坑指南",
      "frontmatter": {
        "title": "移动端踩坑指南",
        "date": "2021-01-28T00:00:00.000Z"
      },
      "regularPath": "/docs/jottings/mobile.html",
      "relativePath": "docs/jottings/mobile.md",
      "key": "v-13eb74bc",
      "path": "/docs/jottings/mobile.html",
      "headers": [
        {
          "level": 2,
          "title": "HTML方向",
          "slug": "html方向"
        },
        {
          "level": 3,
          "title": "调用系统功能",
          "slug": "调用系统功能"
        },
        {
          "level": 3,
          "title": "忽略自动识别",
          "slug": "忽略自动识别"
        },
        {
          "level": 3,
          "title": "弹出数字键盘",
          "slug": "弹出数字键盘"
        },
        {
          "level": 3,
          "title": "唤醒原生应用",
          "slug": "唤醒原生应用"
        },
        {
          "level": 3,
          "title": "禁止页面缩放",
          "slug": "禁止页面缩放"
        },
        {
          "level": 3,
          "title": "禁止页面缓存",
          "slug": "禁止页面缓存"
        },
        {
          "level": 3,
          "title": "禁止字母大写",
          "slug": "禁止字母大写"
        },
        {
          "level": 3,
          "title": "针对Safari配置",
          "slug": "针对safari配置"
        },
        {
          "level": 3,
          "title": "针对其他浏览器配置",
          "slug": "针对其他浏览器配置"
        },
        {
          "level": 3,
          "title": "让:active有效，让:hover无效",
          "slug": "让-active有效，让-hover无效"
        },
        {
          "level": 2,
          "title": "CSS方向",
          "slug": "css方向"
        },
        {
          "level": 3,
          "title": "自动适应布局",
          "slug": "自动适应布局"
        },
        {
          "level": 3,
          "title": "自动适应背景",
          "slug": "自动适应背景"
        },
        {
          "level": 3,
          "title": "监听屏幕旋转",
          "slug": "监听屏幕旋转"
        },
        {
          "level": 3,
          "title": "支持弹性滚动",
          "slug": "支持弹性滚动"
        },
        {
          "level": 3,
          "title": "禁止滚动传播",
          "slug": "禁止滚动传播"
        },
        {
          "level": 3,
          "title": "禁止屏幕抖动",
          "slug": "禁止屏幕抖动"
        },
        {
          "level": 3,
          "title": "禁止长按操作",
          "slug": "禁止长按操作"
        },
        {
          "level": 3,
          "title": "禁止字体调整",
          "slug": "禁止字体调整"
        },
        {
          "level": 3,
          "title": "禁止高亮显示",
          "slug": "禁止高亮显示"
        },
        {
          "level": 3,
          "title": "禁止动画闪屏",
          "slug": "禁止动画闪屏"
        },
        {
          "level": 3,
          "title": "美化表单外观",
          "slug": "美化表单外观"
        },
        {
          "level": 3,
          "title": "美化滚动占位",
          "slug": "美化滚动占位"
        },
        {
          "level": 3,
          "title": "美化输入占位",
          "slug": "美化输入占位"
        },
        {
          "level": 3,
          "title": "对齐输入占位",
          "slug": "对齐输入占位"
        },
        {
          "level": 3,
          "title": "对齐下拉选项",
          "slug": "对齐下拉选项"
        },
        {
          "level": 3,
          "title": "修复点击无效",
          "slug": "修复点击无效"
        },
        {
          "level": 3,
          "title": "识别文本换行",
          "slug": "识别文本换行"
        },
        {
          "level": 3,
          "title": "开启硬件加速",
          "slug": "开启硬件加速"
        },
        {
          "level": 3,
          "title": "描绘像素边框",
          "slug": "描绘像素边框"
        },
        {
          "level": 3,
          "title": "控制溢出文本",
          "slug": "控制溢出文本"
        },
        {
          "level": 2,
          "title": "JS方向",
          "slug": "js方向"
        },
        {
          "level": 3,
          "title": "禁止点击穿透",
          "slug": "禁止点击穿透"
        },
        {
          "level": 3,
          "title": "禁止滑动穿透",
          "slug": "禁止滑动穿透"
        },
        {
          "level": 3,
          "title": "支持往返刷新",
          "slug": "支持往返刷新"
        },
        {
          "level": 3,
          "title": "解析有效日期",
          "slug": "解析有效日期"
        },
        {
          "level": 3,
          "title": "修复输入监听",
          "slug": "修复输入监听"
        },
        {
          "level": 3,
          "title": "简化回到顶部",
          "slug": "简化回到顶部"
        },
        {
          "level": 3,
          "title": "简化懒性加载",
          "slug": "简化懒性加载"
        },
        {
          "level": 3,
          "title": "优化扫码识别",
          "slug": "优化扫码识别"
        },
        {
          "level": 3,
          "title": "自动播放媒体",
          "slug": "自动播放媒体"
        }
      ],
      "lastUpdated": "2023/3/9 11:39:32",
      "size": "15.80kb"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "JS Tags"
      },
      "regularPath": "/tag/JS/",
      "key": "v-e8d965c8",
      "path": "/tag/JS/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "HTML Tags"
      },
      "regularPath": "/tag/HTML/",
      "key": "v-184d950c",
      "path": "/tag/HTML/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "正则 Tags"
      },
      "regularPath": "/tag/%E6%AD%A3%E5%88%99/",
      "key": "v-0c1cbc56",
      "path": "/tag/正则/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "继承 Tags"
      },
      "regularPath": "/tag/%E7%BB%A7%E6%89%BF/",
      "key": "v-c784ecce",
      "path": "/tag/继承/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "原型 Tags"
      },
      "regularPath": "/tag/%E5%8E%9F%E5%9E%8B/",
      "key": "v-3446f207",
      "path": "/tag/原型/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "事件模型 Tags"
      },
      "regularPath": "/tag/%E4%BA%8B%E4%BB%B6%E6%A8%A1%E5%9E%8B/",
      "key": "v-fd10f050",
      "path": "/tag/事件模型/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端小笔记 Categories"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF%E5%B0%8F%E7%AC%94%E8%AE%B0/",
      "key": "v-d2055fbe",
      "path": "/categories/前端小笔记/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "排序 Categories"
      },
      "regularPath": "/categories/%E6%8E%92%E5%BA%8F/",
      "key": "v-85672be2",
      "path": "/categories/排序/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Promise Categories"
      },
      "regularPath": "/categories/Promise/",
      "key": "v-3dfe3db2",
      "path": "/categories/Promise/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "正则 Categories"
      },
      "regularPath": "/categories/%E6%AD%A3%E5%88%99/",
      "key": "v-75f01a3e",
      "path": "/categories/正则/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "继承 Categories"
      },
      "regularPath": "/categories/%E7%BB%A7%E6%89%BF/",
      "key": "v-6753daa5",
      "path": "/categories/继承/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "原型 Categories"
      },
      "regularPath": "/categories/%E5%8E%9F%E5%9E%8B/",
      "key": "v-014579da",
      "path": "/categories/原型/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "事件模型 Categories"
      },
      "regularPath": "/categories/%E4%BA%8B%E4%BB%B6%E6%A8%A1%E5%9E%8B/",
      "key": "v-7ff82de4",
      "path": "/categories/事件模型/"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Page 2 - JS | Tags"
      },
      "regularPath": "/tag/JS/page/2/",
      "key": "v-7f71ddbe",
      "path": "/tag/JS/page/2/"
    }
  ],
  "themeConfig": {
    "mode": "dark",
    "noFoundPageByTencent": true,
    "logo": "https://user-images.githubusercontent.com/84856433/216508004-9c54d340-b92c-4596-b7e5-511ab7f350ab.jpg",
    "valineConfig": {
      "appId": "EyjP4eevrEqbQEnSdjt4fRNF-gzGzoHsz",
      "appKey": "HBRqgs9I8vFisBhlg6mAy5C9"
    },
    "nav": [
      {
        "text": "我的主页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "时间轴",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "学习记录",
        "icon": "reco-document",
        "items": [
          {
            "text": "HTML",
            "link": "/docs/Html/BOM"
          },
          {
            "text": "CSS",
            "link": "/docs/CSS/accordion"
          },
          {
            "text": "JS",
            "link": "/docs/JS/mobile"
          },
          {
            "text": "Vue",
            "link": "/docs/vue/ref"
          }
        ]
      }
    ],
    "sidebar": {
      "/docs/Html/": [
        "BOM",
        "DOM"
      ],
      "/docs/CSS/": [
        "accordion",
        "flexbox",
        "loading",
        "shadow"
      ],
      "/docs/JS/": [
        "mobile",
        "Git",
        "常见Api手写"
      ],
      "/docs/Vue/": [
        {
          "title": "Vue3.0",
          "collapsable": false,
          "children": [
            "ref",
            "asyncComponent",
            "attribute",
            "directive",
            "v-is",
            "Data",
            "event",
            "filters",
            "template",
            "funComponent",
            "API",
            "renderFun",
            "slot",
            "animationClass",
            "v-model",
            "v-if&v-for",
            "v-bind"
          ]
        }
      ],
      "/docs/Nuxt/": [
        {
          "title": "Nuxt",
          "collapsable": false,
          "children": [
            "introduction",
            "asyncData",
            "context"
          ]
        }
      ]
    },
    "type": "blog",
    "blogConfig": {
      "tag": {
        "location": 3,
        "text": "无关紧要"
      }
    },
    "friendLink": [
      {
        "title": "Lucifer",
        "desc": "Everything can be expected in the future.",
        "email": "2050180797@qq.com",
        "logo": "https://nightliuguoxing-github-io.vercel.app/img/avatar.jpg",
        "link": "https://love.liuguoxing.top"
      },
      {
        "title": "午后南杂",
        "desc": "一款简洁而优雅的 vuepress 博客 & 文档 主题。",
        "email": "无",
        "link": "https://vuepress-theme-reco.recoluan.com/"
      }
    ],
    "search": true,
    "searchMaxSuggestions": 10,
    "lastUpdated": "Last Updated",
    "author": "LF",
    "authorAvatar": "https://user-images.githubusercontent.com/84856433/216508004-9c54d340-b92c-4596-b7e5-511ab7f350ab.jpg",
    "record": "",
    "startYear": "2018"
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}